apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadirminio
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
  labels:
    app: minio-storage-claim
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default/minio/minio-0
