apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadirminio
  labels:
    app: minio-storage-claim
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default/minio/minio-0
