apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - port: 9008
      targetPort: 9000
      nodePort: 30098
      protocol: TCP
  selector:
    app: minio
